config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  resources :products
  resources :tags

end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :product_tags,  dependent: :destroy
    has_many :products, :through => :product_tags

    validates :tag, :tag_description, presence: true
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    def index
        @tags = Tag.all
    end
    
    def show
        @tag = Tag.find(params[:id])
        @tagproducts=Tag.find(params[:id]).products
    end
    
    def new
        @tag = Tag.new
    end
    
    def create
        @tag = Tag.new(tag_params)
        if @tag.save
            flash[:success] = "You have created your tag successfully"
            redirect_to @tag
        else
          render :new, status: :unprocessable_entity\
          flash[:alert] = "Tag not created,Try again"
        end
    end

    def edit
        @tag = Tag.find(params[:id])
    end

    
    def update
        @tag = Tag.find(params[:id])
        if @tag.update(tag_params)
            redirect_to @tag
            flash[:success] = "You have updated your tag succesfully"
        else
          render :edit, status: :unprocessable_entity
          flash[:alert] = "Tag not updated,Try again"
        end
    end

    def destroy
        @tag = Tag.find(params[:id])
        @tag.destroy
        redirect_to tags_path, status: :see_other
        flash[:success] = "You have deleted your tag successfully"
    end
    

    private
    def tag_params
        params.require(:tag).permit(:tag,:tag_description)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_with model: @tag do |form| %>
 
    <div class="mb-3">
      <%= form.label :tag %><br>
      <%= form.text_field :tag %><br>
      <% @tag.errors.full_messages_for(:tag).each do |message| %>
        <div class="red"><%= message %></div>
      <% end %>
    </div>
  
    <div class="mb-3">
      <%= form.label :tag_description %><br>
      <%= form.text_area :tag_description %><br>
      <% @tag.errors.full_messages_for(:tag_description).each do |message| %>
        <div class="red"><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.submit "Submit", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/tags/edit.html.erb
<h3 class="tag-new-heading">Editing tag</h3>
<div class="tag-new-form-container">
<%= render "tags/form"%>
</div>

app/views/tags/index.html.erb
<h2 class="tag-index-main-heading">List of tags:</h2>

<table class="table w-100">
        <tr>
            <th>Tag Name</th>
            <th>Description</th>
            <th>Edit</th>
            <th>Destroy</th>
        </tr>
        <% @tags.each do |tag| %>
            <tr>
                <td>
                  <p><%=link_to tag.tag.capitalize, tag%></p>
                </td>
                <td>
                  <%= tag.tag_description.capitalize %>
                </td>
                <td>
                <%= button_to "Edit", edit_tag_path(tag) , method: :get,class:"btn btn-primary"%>
                </td>
                <td>
                  <%= button_to "Destroy", tag_path(tag), data: {
                      turbo_method: :delete,
                      turbo_confirm: "Are you sure?"
                    }, method: :delete,class:"btn btn-danger" %>
                </td>
            </tr>
            <% end %>
        </table>
        
<br/>

<div class="tag-button-container">
<%= button_to "Add tag", new_tag_path,method: :get,class:"btn btn-success" %>
</div> 

app/views/tags/new.html.erb
<h3 class="tag-new-heading">Adding tag</h3>
<div class="tag-new-form-container">
<%= render "tags/form"%>
</div>

app/views/tags/show.html.erb
<h2 class="tag-index-main-heading">Details of <%= @tag.tag%></h2>
<p class="tag-show-heading">Tag Name: <span class="tag-show-span-heading"><%= @tag.tag.capitalize%></span><p/>
<p class="tag-show-heading">Tag Description: <span class="tag-show-span-heading"> <%= @tag.tag_description.capitalize%></p>

<table class="table w-100">
  <tr>
    <th>Tag Name</th>
    <th>Description</th>
    <th>Brand</th>
    <th>Price</th>
  </tr>
  <% @tagproducts.each do |tagproduct| %>
    <tr>
      <td>
        <p><%= tagproduct.product_name.capitalize%></p>
      </td>
      <td>
        <%= tagproduct.product_description.capitalize %>
      </td>
      <td>
        <%= tagproduct.brand.capitalize %>
      </td>
      <td>
        <%= tagproduct.price %>
      </td>
    </tr>
  <% end %>
</table>

<div class="tag-button-container">
<%= button_to "back",tags_path,method: :get,class:"btn btn-warning"%><br/>
</div>